version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: testing_python_app
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: python get_value.py
